disabled = false
languageCode = "en"
languageName = "English"
weight = 1
title = "Team Spiral Racing Blog"

[params]
  displayName = "EN"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "logos/short.png"
  # secondaryLogo = "img/secondary-logo.png"
  description = "Team Spiral Racing Blog"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "Team Spiral Racing"
  email = "contact@teamspiralracing.com"
  image = "logos/icon.png"
  imageQuality = 96
  headline = "Stories from the adventures of TSR"
  bio = "A team driven by passion for canyon and track, finding the perfect balance between street driving and track racing."
